name: Build Factory

on:
    workflow_call:
      inputs:
        tag:
          required: false
          type: string
        image_tag:
          required: true
          type: string
        build_version:
          required: true
          type: string
        iso_folder:
          required: true
          type: string


concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' && !startsWith(github.ref, 'refs/heads/v') && !startsWith(github.ref, 'refs/tags/v') }}
jobs:
  build-binaries:
    name: Build binaries
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        arch: [x64, arm64]
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set Build Environment Variables
      if: ${{ inputs.tag != '' }}
      run: |
        TAG_NAME="${{ inputs.tag }}"
        echo "HARVESTER_UI_VERSION=$TAG_NAME" >> $GITHUB_ENV
        echo "HARVESTER_UI_PLUGIN_BUNDLED_VERSION=$TAG_NAME" >> $GITHUB_ENV
        echo "HARVESTER_INSTALLER_REF=$TAG_NAME" >> $GITHUB_ENV
        echo "HARVESTER_ADDONS_VERSION=$TAG_NAME" >> $GITHUB_ENV

    # Build binaries
    - name: Run make ci
      if: ${{ matrix.arch == 'x64' }}
      run: make ci
    - name: Run make arm
      if: ${{ matrix.arch == 'arm64' }}
      run: make arm

    - name: Upload binaries
      uses: actions/upload-artifact@v4
      with:
        name: binaries_${{ matrix.arch }}_artifact
        path: ./bin/*


  build-iso:
    name: Build ISO
    runs-on: ubuntu-24.04
    if: ${{ startsWith(github.ref, 'refs/heads/') || startsWith(github.ref, 'refs/tags/') }}
    strategy:
      matrix:
        arch: [x64, arm64]
    permissions:
      contents: write # for github prerelease action
      id-token: write # for reading credential https://github.com/rancher-eio/read-vault-secrets
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Declare branch and arch
      run: |
        echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> "$GITHUB_ENV"
        if [ "${{ matrix.arch }}" == "x64" ]; then
          echo "arch=amd64" >> "$GITHUB_ENV"
        else
          echo "arch=arm64" >> "$GITHUB_ENV"
        fi
    
    - name: Set Build Environment Variables
      if: ${{ inputs.tag != '' }}
      run: |
        TAG_NAME="${{ inputs.tag }}"
        echo "HARVESTER_UI_VERSION=$TAG_NAME" >> $GITHUB_ENV
        echo "HARVESTER_UI_PLUGIN_BUNDLED_VERSION=$TAG_NAME" >> $GITHUB_ENV
        echo "HARVESTER_INSTALLER_REF=$TAG_NAME" >> $GITHUB_ENV
        echo "HARVESTER_ADDONS_VERSION=$TAG_NAME" >> $GITHUB_ENV

    - name: build-iso
      if: ${{ startsWith(github.ref, 'refs/heads/') }}
      run: |
        make build-iso
      env:
        REPO: rancher
        DRONE_BRANCH: ${{ env.branch }}

    - name: build-tag-iso
      if: ${{ startsWith(github.ref, 'refs/tags/') }}
      run: |
        make build-iso
      env:
        REPO: rancher
        DRONE_BRANCH: ${{ github.ref_name }}
        DRONE_TAG: ${{ github.ref_name }}

    - name: upload-kernel-initrd-releases
      if: ${{ startsWith(github.ref, 'refs/tags/') }}
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        if gh release view ${{ github.ref_name }} > /dev/null; then
          echo ${{ github.ref_name }} release exists
        else
          gh release create ${{ github.ref_name }} --draft --notes "Draft release for ${{ github.ref_name }}"
        fi
        gh release upload ${{ github.ref_name }} dist/artifacts/harvester*

